### ISSUE TITLE
notebook does not allow first code cell to run because import statement does not include parent module.

### ISSUE THREAD

**Issue by markatango** [Calysto/aima3#1]
change: `from agents import *` to `from aima3.agents import *`
Add note to add to PYTHONPATH: `<aima3 root directory>` so the notebook can find the `aima3.agents` module.

**Comment by dsblank** [comment]
Thanks! Fixed first point via 6908ab5bc4ffa19b40fea90a819c64ac2fdc706a

You should be able to "pip install aima3" or "cd aima3; pip install ." or set the PYTHONPATH, etc. Too many possibilities to list all of them.
